---
-
  hosts: dev
  become: yes
  become_method: sudo
  vars:
    timezone: 'America/Los_Angeles'
    db:
      name: "{{ config.db.name | default('trails') }}"
      host: "{{ config.db.host | default('localhost') }}"
      creds:
        user: "{{ config.db.creds.user | default('trails') }}"
        password: "{{ config.db.creds.password | default('ins3curE') }}"
    domain: "{{ config.domain | default('trails.dev') }}"
    google:
      oauth2:
        client:
          id: "{{ config.google.oauth2.client.id | default('') }}"
          secret: ""{{ config.google.oauth2.client.secret | default('') }}""
  roles:
    - common
    - db
    - web
    - deploy
