---
-
  hosts: dev
  become: yes
  become_method: sudo
  vars:
    timezone: "{{ config.timezone | default('America/Los_Angeles') }}"
    domain: "{{ config.domain | default('trails.dev') }}"
    db_name: "{{ config.db_name | default('trails') }}"
    db_host: "{{ config.db_host | default('localhost') }}"
    db_user: "{{ config.db_user | default('trails') }}"
    db_password: "{{ config.db_password | default('ins3curE') }}"
    google_oauth2_client_id: "{{ config.google_oauth2_client_id | default('') }}"
    google_oauth2_client_secret: "{{ config.google_oauth2_client_secret | default('') }}"
  roles:
    - common
    - db
    - web
    - deploy
