common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: trails
  password: trails
  host: localhost

development:
  <<: *common
  database: trails_development

test:
  <<: *common
  database: trails_test

production:
  <<: *common
  database: trails_production
