---
- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: restart network
  service: name=networking state=restarted

- name: ifup eth1
  command: bash -c "ifdown eth1 && ifup eth1"
